Implement serialization of the only one pokemon
IndividualThoughtPatterns/KotlinApp pull request #1
Opened 2024-07-11 18:50 UTC by IndividualThoughtPatterns

What is implemented for now:
1) A simple class for pokemon with a "name" property only;
2) A network request to pokeapi.co for JSON with info about a pokemon via okhttp3, limited for one object;
3) Serialization of this request JSON object.

I request for the comment on what is done and to clarify the task for further app functionality expansion.

2024-07-11 20:36 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/MainActivity.kt
> +                            val name = results.getJSONObject(0).getString("name")
найс, теперь попробуй сделать список, запросить 20 покемонов, распарсить, и вывести в ресайклер

2024-07-12 13:32 UTC, IndividualThoughtPatterns commented
Вынес класс Pokemon в отдельный файл.
Сделал адаптер и список для вывода запрошенного количества покемонов.

2024-07-12 14:12 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/MainActivity.kt
> +                            }
отлично теперь вот попробуй этот List<String> превратить в List<Pokemon>
ты можеш просто пройтись в цикле, но лучше заюзать функцию map
тоесть
list.map { Pokemon(name = it) }

и в адаптер по итогу принемай List<Pokemon>

2024-07-12 14:14 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
> +class PokemonAdapter(private val names: List<String>) :
сделай метод, типа setPokemons(pokemons: List<Pokemon>) чтоб в него принемались покемоны, а с конструктора убери, иначе потом так не удобно будет

2024-07-12 14:26 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
> +        val pokemonNameTV = itemView.findViewById<TextView>(R.id.pokemonNameTV)
в целом без разницы но принято делать в холдере метод bind в котором ты принемаеш покемона и там делаеш установку значений, тоесть
fun bind(pokmon: Pokemon) {
pokemonNameTV.text = pokemon.name
}

а в методе onBindViewHolder  делаеш

holder.bind(pokemons[position])

2024-07-12 14:29 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/MainActivity.kt
> +                override fun onFailure(call: Call, e: IOException) {
попробуй еще вынести сам запрос и хттпКлиент в другой класс, типа PokemonsNetwork

2024-07-16 14:18 UTC, IndividualThoughtPatterns commented
Применил правки по рекомендациям.

2024-07-16 14:33 UTC, epicarchitect requested changes

2024-07-16 14:33 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
> +    private lateinit var pokemons: List<Pokemon>
лучше делать тут без lateinit, и ваще в целом стараться его избегать, тут лучше сделать 
private var pokemons: List<Pokemon> = emptyList()

2024-07-16 14:33 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
> +        pokemons = pokemonList
у тебя все работет и так, потому что ты сетиш адаптер в ресайклер после того как этот метод вызовеш, а если ты адаптер засетиш сначала а потом этот метод вызовеш у тебя список может не отобразится (ну или в твоем случае с lateinit ваще крашнет)


кароч, когда новые данные ложиш в адаптер, нужно адаптеру об этом сказать, для это есть методы называющиеся со свова notify

в твоем случае хватит notifyDataSetChanged, тебе по сути надо так сделать:
fun setPokemons(pokemonList: List<Pokemon>) {
        pokemons = pokemonList
        notifiDataSetChanged() // вызовет полную перерисовку (можеш методы onBind onCreate ViewHodler залогировать чтоб посмотреть что происходит)
}

можеш еще другие методы потыкать которые там notifyItemChanged и тд

2024-07-16 14:33 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonsNetwork.kt
> +                    pokemons = names.map { Pokemon(name = it) }
красивше будет прост тут написать val pokemons = names.map { Pokemon(name = it) } а там lateinit убрать

2024-07-16 14:40 UTC, epicarchitect requested changes

2024-07-16 14:40 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/MainActivity.kt
> +            }
прикольно ты сделал я никогда так не делал)
крч обычно делают так:
onResult = { pokemons: List<Pokemon> ->

}
или
onResult = { pokemons ->

}
или 
onResult = {
// твои покемены это it
}

2024-07-19 14:10 UTC, merged