Добавил фрагменты в приложение
IndividualThoughtPatterns/KotlinApp pull request #2
Opened 2024-07-26 11:08 UTC by IndividualThoughtPatterns

2024-07-26 11:27 UTC, epicarchitect requested changes

2024-07-26 11:27 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
> +        }
это в bind лучше унести (насамом деле лучше в init {} холдера)

2024-07-26 11:27 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +        fun newInstance() = PokemonListFragment()
вот так лучше не делать

2024-07-26 11:27 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +        fun newInstance() = PokemonListFragment()
ты эт и не юзаеш так что норм, прост удали

2024-07-26 11:27 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
>      class Viewholder(itemView: View) : RecyclerView.ViewHolder(itemView) {
а сделай тут тоже с биндингом

2024-08-03 10:33 UTC, IndividualThoughtPatterns commented
Новый коммит:
1) Внес правки;
2) Добавил картинки в список;
3) Добавил больше информации в InfoFragment.

2024-08-04 00:09 UTC, epicarchitect requested changes

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonAdapter.kt
> +        val avatar_imageVies = binding.avatarImageView
как бы ок, но вот так перекладывать это useless move, яб убрал

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +    }
useless

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +    lateinit var binding: FragmentInfoBinding
как бы ок, но по хорошему надо доку почитать на тему утечек, https://developer.android.com/topic/libraries/view-binding#fragments как минимум чекни как тут делается

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +        val abilities = args.getString("abilities")
теперь сделай чтоб покемон реализовывал Serializeble и бросай его объект в аргументы, вот пример, тут с активити, но с фрагментами так же тк и там и там бандл https://metanit.com/java/android/2.12.php

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +            .into(binding.avatarImageView)
вообще принято устанавливать данные в onViewCreated, разницы то особой нету, но вот принято так

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonListFragment.kt
> +    }
useless

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonListFragment.kt
> +        binding = FragmentMainBinding.inflate(inflater)
правильнее делать так FragmentMainBinding.inflate(inflater, container, false)

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonListFragment.kt
> +        binding = FragmentMainBinding.inflate(inflater)
отдельно раскажу почему

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonListFragment.kt
> +                            counter++
прикольное решение, но можно иначе, сделай вот так чтоб был метод в PokemonsNetwork который будет такой:
`fun getPokemons(limit: Int, onResult: (List<Pokemon>) -> Unit, onError: () -> Unit)`

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonListFragment.kt
> +                            counter++
при этом тебе придется заюзать другие методы, вместо enqueue заюзать execute, и тебе придется подумать как запустить это на другом потоке

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonsNetwork.kt
> +                    val weight = json.getString("weight").toInt().toString()
пришло время научится юзать Gson, чтоб вручную не распарсивать

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonsNetwork.kt
> +                    }
а вот не надо их в строку складывать, пусть будет abilityNames: List<String> в покемоне, ну и с другими списками внутри так же

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonsNetwork.kt
> +                    }
а во фрагменте можеш пока сложить в строку (хотя потом в инфо фрагменте будет ресайклер
, сложный, но эт потом)

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonsNetwork.kt
> +                        baseStats.get(5)
вот в таких ситуациях хорошо бы именовать параметры

2024-08-04 00:09 UTC, epicarchitect commented on app/src/main/res/layout/fragment_main.xml
> +</FrameLayout>
а можно вот так сделать:
```
<androidx.recyclerview.widget.RecyclerView
xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
android:paddingBottom="20dp"
    android:paddingTop="20dp"
 />
```

2024-08-04 00:10 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonListFragment.kt
> +                            counter++
тк execute исполнит запрос там где вызвали

2024-08-04 00:10 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonsNetwork.kt
> +                    val weight = json.getString("weight").toInt().toString()
для этого сначала над разобраться с Serializeble

2024-08-10 15:22 UTC, IndividualThoughtPatterns commented
Внес правки.

2024-08-17 07:39 UTC, IndividualThoughtPatterns commented
Переписал, используя Retrofit.

2024-08-18 14:15 UTC, IndividualThoughtPatterns commented
Вложил классы для Gson в класс Pokemon.
ApiInterface вынес в отдельный файл.

2024-08-21 14:07 UTC, merged