change design in info fragment
IndividualThoughtPatterns/KotlinApp pull request #5
Opened 2024-09-19 10:57 UTC by IndividualThoughtPatterns

Выбранный дизайн: https://www.figma.com/design/WwjXWlJhP98qbpw6QhafAG/Pok%C3%A9dex-(Community)?node-id=314-3&node-type=canvas

Там отображается блок "moves", заменил на "abilities", т.к. изначально запрашивал их, ну и суть похожая.
Само описание покемона непонятно откуда берется там, добавил похожее из того, что нашел в API. 

Есть проблема с отображением блока Base Stats - его расположение должно быть фиксировано снизу, но у меня не получилось его расположить так.
Делал через LinearLayout изначально. Пытался через Constraint, там можно указать layout_constraintBottom_toBottomOf="parent", верстка сломалась и исправить не получилось, вернулся к LinearLayout.
Если у покемона слишком большой текст с описание, блок base stats может не влезть полностью. Пытался добавить прокрутку для него через помещение в ScrollView, чтобы сам элемент был фиксированного размера и текст полностью вмещался, но у меня не сработало это почему-то, убрал.

Также, всякого рода "полосы", которые есть в дизайне скорее всего сделал неправильно, т.к. не нашел правильного способа отображение подобных элементов. Для полос-разделителей, возможно, подошел бы атрибут divider, но я узнал о нем уже после того, как сделал их. Так же с полосами, которые отображают значение характеристик (base stats) покемона, я там впервые воспользовался классами для работы с графикой и указал фиксированный отступ по оси Y для полос, что будет не актуально в случае изменения margin у элементов внутри контейнера.

2024-09-25 08:32 UTC, IndividualThoughtPatterns commented
Заменил ручную отрисовку полос-индикаторов base stats через Canvas на ProgressBar.

2024-09-30 11:01 UTC, epicarchitect requested changes

2024-09-30 11:01 UTC, epicarchitect commented on app/src/main/res/layout/fragment_info.xml
> +                            android:text="6,9 kg"
чтоб такие тестовые данные указывать лучше писать tools:text="test text"

2024-09-30 11:01 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/Pokemon.kt
>      val types: MutableList<String>,
надо бы сделать просто List вместо MutableList

2024-09-30 11:01 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/Pokemon.kt
> +            )}
форматирование, не забывай тупа везде прожимать автоформат, иначе на работе так же буду докапываться до неправильно стоящей скобочки)

2024-09-30 11:01 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/Pokemon.kt
> +            )}
можеш ксткти выделить весь проект слева в иерархии файлов, и прожать автоврмат, прям все нахер отформатируется и будет красиво, чтоб по каждому файлу не бегать

2024-09-30 11:01 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +            typeCardViewList.add(CardView(requireContext()))
интересно ты кнш сделал, в телеге запишу что тут не так

2024-09-30 11:14 UTC, epicarchitect requested changes

2024-09-30 11:14 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +        mainColor = resources.getColor(mainColor)
getColor тебе подчоркивает устаревшим, заюзай ContextCompat.getColor

2024-09-30 11:14 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +        val drawable = resources.getDrawable(mainColor)
а тут ContextCompat.getDrawable

2024-10-07 10:32 UTC, epicarchitect requested changes

2024-10-07 10:32 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +            fillProgressBar = ::fillProgressBar,
fillProgressBar теперь по сути должен быть в BaseStatAdapter.ViewHolder тк он знать должен как нарисовать прогресс баг и данные для этого у него есть

2024-10-07 10:32 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/PokemonInfoFragment.kt
> +            fillProgressBar = ::fillProgressBar,
и так же с getColor для TypesAdapter

2024-10-07 10:32 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/TypesAdapter.kt
> +                    App.instance.applicationContext,
лучше заюзать контекст из вьюхи, itemView.context

2024-10-07 10:32 UTC, epicarchitect commented on app/src/main/java/com/example/kotlinapp/BaseStatAdapter.kt
> +        fun bind(baseStatElement: BaseStat) {
над выучить новый прием так сказать, новую технику, можно сделать вот так:
```
    fun bind(baseStatElement: BaseStat) = with(binding) {
            baseStatsLabelTextView.text = baseStatElement.baseStatName
            baseStatsValueTextView.text = baseStatElement.baseStatStringValue
            baseStatsLabelTextView.setTextColor(color)

            fillProgressBar(
                hpProgressBar,
                baseStatElement.baseStatValue,
                color
            )
        }
```

это тупа ради того чтобы не писать постоянно binding в данном случае, чтоб понимать почему так работает функция with надо понимать вот это:

Function types can optionally have an additional receiver type, which is specified before the dot in the notation: the type A.(B) -> C represents functions that can be called on a receiver object A with a parameter B and return a value C. [Function literals with receiver](https://kotlinlang.org/docs/lambdas.html#function-literals-with-receiver) are often used along with these types.

от сюда https://kotlinlang.org/docs/lambdas.html#function-types

2024-10-09 07:54 UTC, merged